name: bertelsmann
channels:
  - pytorch
  - conda-forge
dependencies:
  # Python
  - python=3.6
  - ipython
  - pip

  # Maths & Data Analysis
  - numpy=1.17
  - scipy=1.3
  - pandas=0.25

  # Plotting
  - matplotlib=3.1
  - seaborn=0.9

  # Machine Learning
  - scikit-learn=0.21

  # Deep Learning
  - pytorch=1.3
  - torchvision=0.4

  # Jupyter
  - jupyter
  - nbstripout
