name: bertelsmannai
channels:
  - pytorch
  - conda-forge
dependencies:
  # Python
  - python=3.7
  - ipython
  - pip

  # Maths & Data Analysis
  - numpy=1.18
  - scipy=1.4
  - pandas=1.0

  # Plotting
  - matplotlib=3.1
  - seaborn=0.10

  # Machine Learning
  - scikit-learn=0.22

  # Deep Learning
  - pytorch=1.4
  - torchvision

  # Jupyter
  - jupyter
  - nbstripout

  # Devtools
  - flake8
  - black
